/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Edge: { // root type
    cursor?: string | null; // String
    node?: NexusGenRootTypes['Project'] | null; // Project
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage?: boolean | null; // Boolean
  }
  Project: { // root type
    id?: number | null; // Int
    image?: string | null; // String
    name?: string | null; // String
  }
  Query: {};
  Repo: { // root type
    id?: number | null; // Int
    title?: string | null; // String
  }
  RepoSummary: { // root type
    count?: number | null; // Int
    repos?: Array<NexusGenRootTypes['Repo'] | null> | null; // [Repo]
  }
  Response: { // root type
    edges?: Array<NexusGenRootTypes['Edge'] | null> | null; // [Edge]
    pageInfo?: NexusGenRootTypes['PageInfo'] | null; // PageInfo
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Edge: { // field return type
    cursor: string | null; // String
    node: NexusGenRootTypes['Project'] | null; // Project
  }
  Mutation: { // field return type
    createProject: NexusGenRootTypes['Project']; // Project!
    createRepo: NexusGenRootTypes['Repo'] | null; // Repo
    deleteProject: NexusGenRootTypes['Project'] | null; // Project
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean | null; // Boolean
  }
  Project: { // field return type
    id: number | null; // Int
    image: string | null; // String
    name: string | null; // String
  }
  Query: { // field return type
    project: NexusGenRootTypes['Project']; // Project!
    projects: NexusGenRootTypes['Response'] | null; // Response
    repoSummary: NexusGenRootTypes['RepoSummary'] | null; // RepoSummary
    repos: Array<NexusGenRootTypes['Repo'] | null> | null; // [Repo]
  }
  Repo: { // field return type
    id: number | null; // Int
    title: string | null; // String
  }
  RepoSummary: { // field return type
    count: number | null; // Int
    repos: Array<NexusGenRootTypes['Repo'] | null> | null; // [Repo]
  }
  Response: { // field return type
    edges: Array<NexusGenRootTypes['Edge'] | null> | null; // [Edge]
    pageInfo: NexusGenRootTypes['PageInfo'] | null; // PageInfo
  }
}

export interface NexusGenFieldTypeNames {
  Edge: { // field return type name
    cursor: 'String'
    node: 'Project'
  }
  Mutation: { // field return type name
    createProject: 'Project'
    createRepo: 'Repo'
    deleteProject: 'Project'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
  }
  Project: { // field return type name
    id: 'Int'
    image: 'String'
    name: 'String'
  }
  Query: { // field return type name
    project: 'Project'
    projects: 'Response'
    repoSummary: 'RepoSummary'
    repos: 'Repo'
  }
  Repo: { // field return type name
    id: 'Int'
    title: 'String'
  }
  RepoSummary: { // field return type name
    count: 'Int'
    repos: 'Repo'
  }
  Response: { // field return type name
    edges: 'Edge'
    pageInfo: 'PageInfo'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createProject: { // args
      image: string; // String!
      name: string; // String!
    }
    createRepo: { // args
      title: string; // String!
    }
    deleteProject: { // args
      projectId: number; // Int!
    }
  }
  Query: {
    project: { // args
      projectId: number; // Int!
    }
    projects: { // args
      after?: number | null; // Int
      first?: number | null; // Int
    }
    repoSummary: { // args
      limit: number; // Int!
      offset: number; // Int!
    }
    repos: { // args
      limit: number; // Int!
      offset: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}